# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: lims_development
  pool: 5
  username: kfallon
  password: 
  min_messages: WARNING
  template: template0  #template0 resolves an issue with SQL_ASCII vs UTF-8 encoding


test:
  adapter: postgresql
  encoding: unicode
  database: lims_test
  template: template0
  pool: 5
  username: <%= ENV['LIMS_USERNAME'] %>
  password: <%= ENV['LIMS_PASSWORD'] %>
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: lims_production
  pool: 5
  username: deployer
  password:
  min_messages: WARNING
  template: template0
